language: scala

scala:
  - 2.13.1

os: linux

jdk:
  - oraclejdk11

services:
  - docker

jobs:
  include:
    - stage: test
      name: Unit tests
      script: sbt clean coverage test coverageReport
      after_success:
        # Requires CODECOV_TOKEN env var
        - bash <(curl -s https://codecov.io/bash)
    - name: Integration tests
      script: sbt clean it:test
    - name: End-to-end tests
      script: sbt clean e2e:test
    - name: Linting
      script: sbt clean scalafmtCheck test:scalafmtCheck it:scalafmtCheck

# Caching to speed up runs
# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
