apiVersion: v1
kind: Service
metadata:
  name: simple-temple-test-user
  labels:
    app: simple-temple-test-user
    kind: service
spec:
  ports:
  - name: api
    port: 1026
    targetPort: 1026
  - name: prom
    port: 1027
    targetPort: 1027
  selector:
    app: simple-temple-test-user
    kind: service
