apiVersion: v1
kind: Service
metadata:
  name: simple-temple-test-group
  labels:
    app: simple-temple-test-group
    kind: service
spec:
  ports:
  - name: api
    port: 1030
    targetPort: 1030
  selector:
    app: simple-temple-test-group
    kind: service
