apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    kind: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      kind: service
  template:
    metadata:
      name: auth
      labels:
        app: auth
        kind: service
    spec:
      hostname: auth
      containers:
      - image: simple-temple-test-auth
        name: auth
        ports:
        - containerPort: 1024
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
