apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
    kind: service
spec:
  ports:
  - name: api
    port: 1024
    targetPort: 1024
  - name: prom
    port: 1025
    targetPort: 1025
  selector:
    app: auth
    kind: service
