apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
  labels:
    app: booking
    kind: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
      kind: db
  strategy:
    type: Recreate
  template:
    metadata:
      name: booking-db
      labels:
        app: booking
        kind: db
    spec:
      hostname: booking-db
      containers:
      - env:
        - name: PGUSER
          value: postgres
        image: postgres:12.1
        name: booking-db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: booking-db-claim
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
          name: booking-db-init
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - psql -U postgres -f /docker-entrypoint-initdb.d/init.sql && echo done
      restartPolicy: Always
      volumes:
      - name: booking-db-init
        configMap:
          name: booking-db-config
      - name: booking-db-claim
        persistentVolumeClaim:
          claimName: booking-db-claim
