apiVersion: v1
kind: Service
metadata:
  name: booking-db
  labels:
    app: booking
    kind: db
spec:
  ports:
  - name: db
    port: 5432
    targetPort: 5432
  selector:
    app: booking
    kind: db
