apiVersion: v1
kind: Service
metadata:
  name: booking
  labels:
    app: booking
    kind: service
spec:
  ports:
  - name: api
    port: 1028
    targetPort: 1028
  - name: prom
    port: 1029
    targetPort: 1029
  selector:
    app: booking
    kind: service
