name: Scala CI

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Run tests
      run: sbt test
    - name: Scalafmt Action
      uses: openlawteam/scalafmt-ci@v2.0.2
      with:
        # This will list all the files which do not match the formatter
        args: --list --config .scalafmt.conf

  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Coverage Report
      run: sbt clean coverage test coverageReport
    - name: Upload Reports
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash)
